"""
Agent Approval via Hyperliquid Python SDK

Decrypts the Master EOA key from Vault (just-in-time), creates an
Exchange instance, and calls approve_agent(). The SDK handles all
EIP-712 phantom agent signing internally.

The Agent Key (trading key, no withdrawal rights) is generated by
the SDK itself and returned for storage.
"""

from typing import Dict, Any

from eth_account import Account

import structlog

from app.services.vault.client import VaultEncryptionService

logger = structlog.get_logger(__name__)

# Hyperliquid API URLs
HL_MAINNET_API = "https://api.hyperliquid.xyz"
HL_TESTNET_API = "https://api.hyperliquid-testnet.xyz"


async def approve_agent_with_sdk(
    mission_id: str,
    vault: VaultEncryptionService,
    encrypted_master_key: str,
    is_mainnet: bool,
) -> Dict[str, Any]:
    """
    Use the hyperliquid-python-sdk to approve an agent wallet.

    Flow:
    1. Decrypt Master EOA key from Vault (JIT)
    2. Create SDK Exchange instance with the raw key
    3. Call exchange.approve_agent() — SDK handles EIP-712 internally
    4. Return agent address + private key for storage
    5. Delete raw Master EOA key from memory

    Args:
        mission_id: The mission being activated
        vault: VaultEncryptionService for key decryption
        encrypted_master_key: Vault ciphertext from DB
        is_mainnet: True for mainnet, False for testnet

    Returns:
        {
            "agent_address": "0x...",
            "agent_private_key": "0x...",
            "success": True/False,
            "error": None or "error message",
        }
    """
    master_key = None
    try:
        # 1. Decrypt Master EOA key (JIT — lives in memory only briefly)
        master_key = await vault.decrypt_private_key(encrypted_master_key)
        master_account = Account.from_key(master_key)

        logger.info(
            "Master EOA decrypted for agent approval",
            mission_id=mission_id,
            master_address=master_account.address,
        )

        # 2. Create SDK Exchange instance
        from hyperliquid.exchange import Exchange

        base_url = HL_MAINNET_API if is_mainnet else HL_TESTNET_API
        exchange = Exchange(wallet=master_account, base_url=base_url)

        # 3. Approve agent — SDK generates agent key and signs approval
        result, agent_key = exchange.approve_agent(name="MoleApp Trading Agent")

        agent_account = Account.from_key(agent_key)

        logger.info(
            "Agent approved on Hyperliquid via SDK",
            mission_id=mission_id,
            agent_address=agent_account.address,
        )

        # 4. Encrypt the agent key via Vault before it leaves this process
        #    This prevents the raw key from ever traversing the network.
        agent_key_ciphertext = await vault.encrypt_private_key(agent_key)

        # Audit: record successful agent approval
        from app.services.database import record_agent_audit
        await record_agent_audit(
            node="lifecycle",
            action="agent_approved",
            mission_id=mission_id,
            metadata={
                "agent_address": agent_account.address,
                "master_address": master_account.address,
                "is_mainnet": is_mainnet,
            },
            success=True,
        )

        return {
            "agent_address": agent_account.address,
            "agent_key_ciphertext": agent_key_ciphertext,
            "success": True,
            "error": None,
        }

    except Exception as e:
        logger.error(
            "Agent approval via SDK failed",
            mission_id=mission_id,
            error=str(e),
        )

        # Audit: record failed approval
        try:
            from app.services.database import record_agent_audit
            await record_agent_audit(
                node="lifecycle",
                action="agent_approval_failed",
                mission_id=mission_id,
                error_message=str(e),
                success=False,
            )
        except Exception:
            pass  # Don't let audit failure mask the original error

        return {
            "agent_address": None,
            "agent_key_ciphertext": None,
            "success": False,
            "error": str(e),
        }
    finally:
        # Memory safety: clear all key material
        if master_key is not None:
            del master_key
        try:
            del agent_key
        except NameError:
            pass
        # Also clear SDK references that hold key copies
        try:
            del master_account
        except NameError:
            pass
        try:
            del exchange
        except NameError:
            pass
        try:
            del agent_account
        except NameError:
            pass
